### ISSUE TITLE
Deprecation of this repository

### ISSUE THREAD

**Issue by sbesson** [openmicroscopy/sphinx-ignore-links#1]
While this repository helped us with managing the broken Sphinx links, we found a few caveats throughout the years:

- the requirement to check out another repository in `conf.py` prevented to run sphinx build command offline and we had to work around it - https://github.com/openmicroscopy/ome-documentation/pull/304
- most of these links are specific to a particular documentation set rather than being project-wide
- the existence of this externally managed list makes the documentation linkcheck effectively dependent on the state of this repository with all associated reproducibility issues

As @hflynn already performed a clean step of this repository, a further step would be to deprecate it fully and let individual documentation repositories fully manage their own list of exclusions via `conf.py` and `linkcheck_ignore` parameters.

**Comment by hflynn** [comment]
The ome-internal docs don't reference this repo in the conf.py so I think that is a PR open against repo that does use it now. Once they are all merged, I'll close this issue and we can deprecate the repo.

**Comment by sbesson** [comment]
Following the set of PRs above, I can see no more public usage of this repository across our organizations = see https://github.com/search?utf8=%E2%9C%93&q=sphinx-ignore-links+in%3Afile+user%3Aome++user%3Aopenmicroscopy+user%3AIDR&type=Code.

@hflynn I have updated the description of this repository. Do we want to have a minimal README expressing the deprecation state as well.

**Comment by joshmoore** [comment]
I'd suggest https://help.github.com/articles/archiving-a-github-repository/

**Comment by sbesson** [comment]
Or that :) We haven't used it but probably the feature is recent. If we estimate the impact is low-enough (could it break builds on non-default branches?), happy to go that route.

**Comment by hflynn** [comment]
I've added a README but archiving looks like a good option too

**Comment by hflynn** [comment]
I assume I don't have the permissions to archive this, I certainly can't see the option anywhere.

**Comment by joshmoore** [comment]
For me this is under https://github.com/openmicroscopy/sphinx-ignore-links/settings

![screen shot 2017-11-20 at 16 42 30](https://user-images.githubusercontent.com/88113/33026880-d53ed994-ce11-11e7-8336-3098ad999c54.png)

**Comment by hflynn** [comment]
Ah, I don't have access the settings tab, I just get a 404 when I click on that URL

**Comment by hflynn** [comment]
I'm pretty sure there would be no impact of archiving this though - it just means any OMERO 5.3.x docs release would require https://github.com/openmicroscopy/ome-documentation/pull/1808 and https://github.com/openmicroscopy/ome-documentation/pull/1810 but that'd be obvious anyway as we'd be using the develop-merge build so they'd be required to get it green.

**Comment by joshmoore** [comment]
Or if necessary, we could unarchive which is certainly the benefit.

**Comment by hflynn** [comment]
👍 to archiving from me

**Comment by sbesson** [comment]
Closing then archiving.
